-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS User CASCADE;
DROP TABLE IF EXISTS Customer CASCADE;
DROP TABLE IF EXISTS Employee CASCADE;
DROP TABLE IF EXISTS Customervisit CASCADE;